export enum Category {
  ALCOHOL = "Alcohol",
  CLOTHES = "Clothes",
  COMMUNICATION = "Communication",
  ENTERTAINMENT = "Entertainment",
  FITNESS = "Fitness",
  FOOD = "Food",
  GIFTS = "Gifts",
  HEALTH = "Health",
  HOME_IMPROVEMENT = "Home Improvement",
  INTERNET_SERVICES = "Internet Services",
  INVESTMENT = "Investment",
  MORTGAGE = "Mortgage",
  OTHER = "Other",
  PERSONAL = "Transportation",
  TRANSPORTATION = "Transportation",
  TRAVEL = "Travel",
  UTILITIES = "Utilities",
}
